# general settings
name: OCTA_Artifact_Removal
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /nfs/gt/train/
    dataroot_lq: /nfs/lq/train/
    geometric_augs: false
    filename_tmpl: '{}'
    io_backend:
      type: disk


    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1

 
    mini_batch_sizes: [1]   
    iters: [300000]
    gt_size: 256   
    gt_sizes: [256]
 

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage

 
    dataroot_gt: /nfs/gt/val/
    dataroot_lq: /nfs/lq/val/

    io_backend:
      type: disk


network_g:
  type: OSAT_HFormer
  inp_channels: 1
  out_channels: 1
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads:  [1,2,4,8]
  heads_v: [1,1,1,1]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False


path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  pixel_opt:
    type: CharbonnierLoss_
    loss_weight: 1
    reduction: mean

val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: true
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: 
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    
    ssim: 
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false


logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 39277
